name = "CFAR"
uuid = "559e7787-0cef-4422-a425-6eaa4ea9c458"
authors = ["Sasha Petrenko <sap625@umsystem.edu>"]
version = "0.1.0"

[deps]
AdaptiveResonance = "3d72adc0-63d3-4141-bf9b-84450dd0395b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrecompileSignatures = "91cefc8d-f054-46dc-8f8c-26e11d7c5411"

[compat]
DocStringExtensions = "0.9"
AdaptiveResonance = "0.8"
DrWatson = "2"
PrecompileSignatures = "3"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
