name: "art-dist"
exp: "art_exp"
rng_seed: 1

feature_bounds:
  min: [
    0.0,
    0.0
  ]
  max: [
    10.0,
    10.0
  ]

# Results destination directory
results:
  - 1_gaussian
  - art

# Parsed options
procs: 10

varying:
  travel:
    lb: 0
    ub: 10
    n_points: 1000


opts_SFAM:
  rho: 0.7

# opts_DDVFA:
#   rho_lb: 0.4
#   rho_ub: 0.75
#   similarity: "single"

# opts_DVFA:
#   rho_lb: 0.4
#   rho_ub: 0.75
