name: "art-dist"
# exp: "art_exp"
exp: "art_dist_exp"
# rng_seed: 1
n_epochs: 1
post: true

# Number of processes to run in parallel
# procs: 10
# procs: 32     # PC 3950X
procs: 16       # Mac M4 Max

feature_bounds:
  min: [
    -20.0,
    0.0
  ]
  max: [
    10.0,
    20.0
  ]

# Results destination directory
results:
  - 1_gaussian
  - art_dist_2

varying:
  rng_seed:
    lb: 1
    ub: 100
    n_points: 10
  travel:
    lb: 0
    ub: 20
    # ub: 10
    n_points: 100
  rho:
    lb: 0.1
    ub: 1.0
    n_points: 10

# opts_SFAM:
#   rho: 0.7

# opts_DDVFA:
#   rho_lb: 0.4
#   rho_ub: 0.75
#   similarity: "single"

# opts_DVFA:
#   rho_lb: 0.4
#   rho_ub: 0.75
