name: "cvi"
exp: "cvi_exp"
# travel_lb: 0
# travel_ub: 10
rng_seed: 1234
n_points: 1000

# Results destination directory
results:
  - 1_gaussian
  - cvi

# Number of processes to run in parallel
# procs: 10
# procs: 32     # PC 3950X
procs: 16       # Mac M4 Max

varying:
  travel:
    lb: 0
    ub: 20
    n_points: 1000
