name: "cvi"
exp: "cvi_exp"
# travel_lb: 0
# travel_ub: 10
rng_seed: 1234
n_points: 1000

# Results destination directory
results:
  - 1_gaussian
  - cvi

# Parsed options
procs: 10

varying:
  travel:
    lb: 0
    ub: 10
    n_points: 1000