# High-level options
n_points_per: 100
dim: 2
rng_seed: 1234
angle: 135
mover: 3

# Distribution parameters
dists:
  1:
    mu: [
      6.0,
      8.0
    ]
    var: [
      [1.0, -0.5],
      [-0.5, 1.0]
    ]
    scale: 1.0
  2:
    mu: [
      0.0,
      6.0
    ]
    var: [
      [1.0, 0.0],
      [0.0, 1.0]
    ]
    scale: 1.0
  3:
    mu: [
      6.0,
      0.0
    ]
    var: [
      [1.0, 0.0],
      [0.0, 1.0]
    ]
    scale: 1.0

