name: "knn-dist"
exp: "knn_dist_exp"
n_epochs: 1
post: true
# n_points: 1000

# Number of processes to run in parallel
# procs: 10
procs: 32     # PC 3950X
# procs: 16       # Mac M4 Max
# procs: 1


# Results destination directory
results:
  - 1_gaussian
  - knn

varying:
  rng_seed:
    lb: 1
    ub: 50
    n_points: 50
    # n_points: 5
  travel:
    lb: 0
    ub: 20
    # ub: 10
    n_points: 101
    # n_points: 20
  k:
    lb: 1
    ub: 101
    n_points: 51
